version: '3'

services:

  odoo:
    build:
      context:
        ./
      args:
        - DEV_MODE=${DEV_MODE}
    ports:
      - "8066:8069"
      - "8072:8072"
    restart: always
#    command: python3 <(curl -s https://upgrade.odoo.com/upgrade) test -d test -t 17.0
#    command: yes > /dev/null
#    command: odoo -u netsuite_integration
    command: /mnt/commands/odoo.sh
#    command: >
#       sh -c "envsubst < /mnt/extra-addons/netsuite_integration/data/ns.integration.setup.csv.template > /mnt/extra-addons/netsuite_integration/data/ns.integration.setup.csv \
#             && odoo -u netsuite_integration"
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./commands:/mnt/commands
      - ./enterprise:/mnt/enterprise
#      - ./odoo/addons/base:/usr/lib/python3/dist-packages/odoo/addons/base
#      - ./odoo/core/addons/sale:/usr/lib/python3/dist-packages/odoo/addons/sale
      - ./odoo/core/addons/account:/usr/lib/python3/dist-packages/odoo/addons/account
#      - ./odoo/addons/base_import:/usr/lib/python3/dist-packages/odoo/addons/base_import
#      - ./odoo/addons/service:/usr/lib/python3/dist-packages/odoo/service
#      - ./odoo/core/models.py:/usr/lib/python3/dist-packages/odoo/models.py
#      - ./odoo/core/modules:/usr/lib/python3/dist-packages/odoo/modules
      - odoo_data16:/var/lib/odoo
    env_file:
      - .env
    environment:
      - HOST=postgresql
      - USER=odoo
      - PASSWORD=odoo
      - DATA_DIR=/mnt/extra-addons/netsuite_integration/data
    depends_on:
      - postgresql

  postgresql:
    image: "postgres:15.2-alpine"
    ports:
      - "5467:5432"
    restart: always
    command: postgres -c 'max_connections=500'
    volumes:
#      - pg_data16_10:/var/lib/postgresql/data
      - pg_data16_11:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo


volumes:
  odoo_data16: {}
  pg_data16: {}
  pg_data16_10: {}
  pg_data16_11: {}
